[v1]
"cargo-deny 0.14.2 (path+file:///mnt/disks/build-disk/src/android/rust-1.73.0/toolchain/cargo-deny)" = ["cargo-deny"]
"cargo-vet 0.8.0 (path+file:///mnt/disks/build-disk/src/android/rust-1.73.0/toolchain/cargo-vet)" = ["cargo-vet"]
