name: "S25Ultra-GKI内核编译"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y curl wget unzip zip git build-essential libssl-dev bc python3 flex bison libelf-dev lz4 cpio dos2unix pahole dwarves

      - name: 集成 KernelSU
        run: |
          cd kernel_platform/common
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s gki

      - name: 自定义内核配置
        run: |
          # 使用追加模式直接写入配置，这种方式在 YAML 中最稳
          cd kernel_platform
          echo "CONFIG_UH=n" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KNOX_NCM=n" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_RKP=n" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KDP=n" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LOCALVERSION_AUTO=n" >> common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_LOCALVERSION="SukiSU-Ultra"' >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KPM=y" >> common/arch/arm64/configs/gki_defconfig
          echo "# CONFIG_FIVE is not set" >> common/arch/arm64/configs/gki_defconfig
          echo "# CONFIG_PROCA is not set" >> common/arch/arm64/configs/gki_defconfig

      - name: 开始编译
        run: |
          chmod +x build_kernel_GKI.sh
          ./build_kernel_GKI.sh pa3q_chn_openx user sun

      - name: 打包 AnyKernel3
        run: |
          mkdir -p output
          git clone --depth=1 https://github.com/topjohnwu/AnyKernel3.git
          
          find kernel_platform/out -name Image -exec cp {} AnyKernel3/ \;
          find kernel_platform/out -name "*.dtbo" -exec cp {} AnyKernel3/ \;
          
          mkdir -p AnyKernel3/modules/lib/modules/
          find kernel_platform/out -name "*.ko" -exec cp {} AnyKernel3/modules/lib/modules/ \;
          
          cd AnyKernel3
          zip -r9 ../S25Ultra_GKI_Kernel.zip ./*
          cd ..
          mv S25Ultra_GKI_Kernel.zip output/

      - name: 上传内核包
        uses: actions/upload-artifact@v4
        with:
          name: S25Ultra-GKI-Kernel
          path: output/S25Ultra_GKI_Kernel.zip

      - name: 自动清理历史失败记录
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
          CURRENT_RUN_ID: ${{ github.run_id }}
        run: |
          WORKFLOW_FILE="Kernel.yml"
          echo "正在清理历史失败记录..."
          TARGET_IDS=$(gh run list --workflow "$WORKFLOW_FILE" --json databaseId,status \
            --jq '.[] | select(.status=="failure" or .status=="cancelled") | .databaseId')
          
          for run_id in $TARGET_IDS; do
            if [ "$run_id" != "$CURRENT_RUN_ID" ]; then
              gh run delete "$run_id"
            fi
          done
        continue-on-error: true

